-- ======================================
-- Nom du fichier : requetes_stage.sql
-- Dates : Septembre/Octobre 2014
-- Rôle : Contient les ordres SQL effecutés dans le module "stage"
-- Auteur(s) : Anthony Lozano
-- ======================================

-- ======================================
-- Afficher les information sur les stages 
-- 

	SELECT ID_STAGE,
		   STAGE.ID_TUTEUR, NOM_TUTEUR, PRENOM_TUTEUR, TEL_TUTEUR, MAIL_TUTEUR,
		   STAGE.ID_PROF, PROF_TUTEUR.MAT_PROF MAT_PROF_TUTEUR,
		   STAGE.ID_PROF_VISITER, PROF_VISITEUR.MAT_PROF MAT_PROF_VISITEUR,
		   STAGE.ID_ETU, NOM_ETU, PRENOM_ETU,
		   STAGE.ID_ENTREPRISE, NOM_ENTREPRISE
	FROM STAGE
	INNER JOIN TUTEUR ON STAGE.ID_TUTEUR = TUTEUR.ID_TUTEUR
	INNER JOIN PROFESSEUR PROF_TUTEUR ON STAGE.ID_PROF = PROF_TUTEUR.ID_PROF
	INNER JOIN PROFESSEUR PROF_VISITEUR ON STAGE.ID_PROF_VISITER = PROF_VISITEUR.ID_PROF
	INNER JOIN ETUDIANT ON STAGE.ID_ETU = ETUDIANT.ID_ETU
	INNER JOIN ENTREPRISE ON STAGE.ID_ENTREPRISE = ENTREPRISE.ID_ENTREPRISE
	-- WHERE CLASSE_STAGE = 'SIO1'; 

-- ======================================
-- Mettre à jour les données sur les stages
--

	UPDATE ID_STAGE, ID_ETU, PRENOM_ETU, NOM_ETU, ID_ENTREPRISE, NOM_ENTREPRISE, ADRESSE_ENTREPRISE, ID_TUTEUR, PRENOM_TUTEUR, NOM_TUTEUR, TEL_TUTEUR, MAIL_TUTEUR, ID_PROF PROF_TUTEUR.MAT_PROF MAT_PROF_TUTEUR, PROF_VISITEUR.MAT_PROF MAT_PROF_VISITEUR
	FROM STAGE 
	INNER JOIN ETUDIANT ON STAGE.ID_ETU = ETUDIANT.ID_ETU
	INNER JOIN ENTREPRISE ON STAGE.ID_ENTREPRISE= ENTREPRISE.ID_ENTREPRISE
	INNER JOIN TUTEUR ON STAGE.ID_TUTEUR = TUTEUR.ID_TUTEUR
	INNER JOIN PROFESSEUR PROF_TUTEUR ON STAGE.ID_PROF = PROF_TUTEUR.ID_PROF
	INNER JOIN PROFESSEUR PROF_VISITEUR ON STAGE.ID_PROF_VISITER = PROF_VISITEUR.ID_PROF;
	WHERE ID_STAGE = ID_STAGE;